version: "3.0"
services:
    db1:
        image: mongo:latest
        restart: always
        build: .
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
    db2:
        image: mongo:latest
        restart: always
        build: .
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
    db3:
        image: mongo:latest
        restart: always
        build: .
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
    adminer:
        image: adminer
        ports:
            - "8080:8080"
